version: '2'

services:
  pio_db:
    image: postgres:9.6
    container_name: pio_db
    environment:
      - POSTGRES_USER=predictionio
      - POSTGRES_PASSWORD=1234

  elasticsearch:
    image: elasticsearch:5.6.14
    container_name: elasticsearch
    ports:
    - 9200:9200
#    - 9300:9300
    volumes:
    - ./files/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g

  pio:
    build: .
    image: predictionio
    container_name: pio
    depends_on:
    - pio_db
    - elasticsearch
    volumes:
    - ./files/pio-env.sh:/opt/pio/conf/pio-env.sh
    command: /etc/service/pio_event/run
    ports:
    - 7070:7070

  pio_queries:
    build: .
    image: predictionio
    container_name: pio_queries
    depends_on:
    - pio
    - pio_db
    - elasticsearch
    volumes:
    - ./files/pio-env.sh:/opt/pio/conf/pio-env.sh
    - ./universal-recommender/engine.json:/root/ur/engine.json
    command: /etc/service/pio_query/run
    ports:
    - 8000:8000
