version: '2'

services:
  hbase:
    image: hyness/hbase-rest-standalone 
    container_name: hbase
    volumes:
        - ./files/hbase/hbase-server-config.xml:/opt/hbase/conf/hbase-site.xml # The config file
        - ./files/hbase/hbase-data/:/data/hbase
        - ./files/hbase/zookeeper-data/:/data/zookeeper
    hostname: hbase

  elasticsearch:
    image: elasticsearch:5.6.14
    container_name: elasticsearch
    ports:
    - 9200:9200
#    - 9300:9300
    volumes:
    - ./files/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g

  pio:
    build: .
    image: predictionio
    container_name: pio
    depends_on:
    - hbase
    - elasticsearch
    volumes:
    - ./files/pio-env.sh:/opt/pio/conf/pio-env.sh
    - ./files/hbase/hbase-client-config.xml:/opt/pio/vendors/hbase/conf/hbase-site.xml
    command: /etc/service/pio_event/run
    ports:
    - 7070:7070

  pio_queries:
    build: .
    image: predictionio
    container_name: pio_queries
    depends_on:
    - pio
    - hbase
    - elasticsearch
    volumes:
    - ./files/pio-env.sh:/opt/pio/conf/pio-env.sh
    - ./files/hbase/hbase-client-config.xml:/opt/pio/vendors/hbase/conf/hbase-site.xml
    - ./universal-recommender/engine.json:/root/ur/engine.json
    command: /etc/service/pio_query/run
    ports:
    - 8000:8000
