#!/usr/bin/env bash

until $(curl --output /dev/null --silent --head --fail http://pio:7070); do
    printf '.'
    sleep 5
done

sleep 2

cd /root/ur

echo ""
echo "Checking status, should exit if pio is not running."
pio status
pio app new handmade || true

echo ""
echo "Checking to see if handmade app exists, should exit if not."
pio app show handmade

pio app data-delete handmade -f

echo ""
echo "Importing sample data"
# get the access_key from pio app list
ACCESS_KEY=`pio app show handmade | grep Key | cut -f 7 -d ' '`
echo -n "Access key: "
echo $ACCESS_KEY
python3 examples/import_handmade.py --access_key $ACCESS_KEY --file data/sample-handmade-data.txt  --url http://pio:7070

echo ""
echo "Building and delpoying model"
pio build --clean
pio train  -- --driver-memory 4g --executor-memory 4g
echo "Model will remain deployed after this test"
pio deploy
